version: "3.2"

services:
  nodejs:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./janus-gateway/html:/app/public
      - ./server/keys:/sslkeys
      - ./server/src:/app
      - /app/node_modules
    ports:
      - "80:80"
      - "443:443"

  jcli:
    build:
      context: ./jcli
      dockerfile: Dockerfile.dev
    volumes:
      - ./jcli/src:/app
      - /app/node_modules

  janus:
    build:
      context: .
      dockerfile: Dockerfile.dev
    #network_mode: "host"
    ports:
      - "8088:8088"
      - "8089:8089"
      - "8188:8188"
